#server:
#  servlet.context-path: /api/rest/v1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jiris
    username: jiris
    password: jiris

  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  resources:
    static-locations: file:src/main/resources/static/
    cache:
      period: 0
